netlify[build]
  command = "npx tailwindcss -i ./src/input.css -o ./src/styles.css --minify"
  publish = "src"
  [[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; script-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Permissions-Policy = "geolocation=()"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"